# Config file for the acts_as_solr plugin.
#
# If you change the host or port number here, make sure you update 
# them in your Solr config file

development:
  url: http://127.0.0.1:8982/solr
  timeout: 60
  
production:
  url: http://127.0.0.1:8983/solr
  timeout: 60

test:
  url: http://127.0.0.1:8981/solr
  timeout: 60
